### ISSUE TITLE
Aggiungere le istruzioni ip route

### ISSUE THREAD

**Issue by Fanfarillo** [Fanfarillo/progetto-NSD#1]
Nei file di configurazione dei router mancano le istruzioni per effettuare il routing (il forwarding) dei pacchetti verso router NON vicini.

**Comment by Fanfarillo** [comment]
In particolare, dobbiamo preoccuparci del routing dei pacchetti che viaggiano tra i due AS (AS-100, AS-200).

**Comment by Sara-DaCanal** [comment]
Gli unici messaggi bgp che arrivano a rb1 sono messaggi di keep alive, se riusciamo a fargli arrivare i messaggi bgp è meglio

**Comment by Sara-DaCanal** [comment]
SE USIAMO INDIRIZZI PUBBLICI TRA GLI AS GLI AS PINGANO. Dobbiamo solo usare gli indirizzi pubblici

**Comment by Sara-DaCanal** [comment]
Le route non servono la roba pinga anche senza ora
