### ISSUE TITLE
Opzione MASQUERADE nel firewall di CE-A1

### ISSUE THREAD

**Issue by Fanfarillo** [Fanfarillo/progetto-NSD#2]
Se impostiamo l'opzione MASQUERADE per mascherare l'indirizzo IP sorgente dei pacchetti provenienti dalla LAN-A1, quest'ultima non sarà in grado di ricevere dei messaggi di risposta, dato che i router non sanno cosa farsene dei pacchetti con indirizzo IP destinazione = "qualcosa di mascherato".
Non so se l'indirizzo IP visto dagli host e dai router esterni alla LAN-A1 è proprio 100.1.12.2: in tal caso, potrebbe anche essere sufficiente istruire i router che, per instradare i pacchetti verso 100.1.12.2, è sufficiente inoltrarli a PE-A2.
Comunque sia, il professore stava valutando se eliminare proprio l'opzione di MASQUERADE dalle specifiche del progetto.

**Comment by Sara-DaCanal** [comment]
masquerade funziona, di nuovo non sapevamo cosa testare.

**Comment by Sara-DaCanal** [comment]
Al firewall manca capire che fare con DNAT e poi funziona tutto
