### ISSUE TITLE
Macsec Key Agreement è deplorevole

### ISSUE THREAD

**Issue by Fanfarillo** [Fanfarillo/progetto-NSD#3]
Anzitutto non mi piace il fatto che le connessioni di Macsec durino una quantità limitata di tempo.
Dopodiché è necessario capire se va bene utilizzare esattamente due interfacce per CE-A1 (enp0s3, enp0s8), con enp0s8 (i.e. l'interfaccia utilizzata per Macsec) come unica interfaccia rivolta verso la LAN-A1.

**Comment by Sara-DaCanal** [comment]
Il tempo limitato è stato risolto: le nostre connessioni macsec non funzionavano, mancava qualcosa sulla configurazione. Ora abbiamo una connessione macsec stabile

**Comment by Sara-DaCanal** [comment]
L'interfaccia basta una! Il problema non era quello è che non avevamo capito niente
